"""initial schema

Revision ID: 2b56329d65d3
Revises: 
Create Date: 2026-04-21 16:54:39.732879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b56329d65d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.Integer(), nullable=True),
    sa.Column('ir_id', sa.Integer(), nullable=True),
    sa.Column('investor_ids', sa.JSON(), nullable=True),
    sa.Column('content_type', sa.Enum('meeting_minutes', 'industry_report', 'daily_push', 'milestone_message', 'investor_list'), nullable=True),
    sa.Column('action', sa.Enum('approved', 'modified', 'rejected'), nullable=True),
    sa.Column('original', sa.Text(length=4294967295), nullable=True),
    sa.Column('final', sa.Text(length=4294967295), nullable=True),
    sa.Column('diff_ratio', sa.Float(), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('response_time_s', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_feedback_ir_id'), 'agent_feedback', ['ir_id'], unique=False)
    op.create_index(op.f('ix_agent_feedback_trace_id'), 'agent_feedback', ['trace_id'], unique=False)
    op.create_table('agent_traces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=True),
    sa.Column('ir_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('skills_called', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('success', 'retry', 'failed'), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_traces_ir_id'), 'agent_traces', ['ir_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_thread_id'), 'agent_traces', ['thread_id'], unique=False)
    op.create_table('interaction_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('ir_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('meeting', 'email', 'wechat', 'push', 'call', 'other'), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(length=4294967295), nullable=True),
    sa.Column('agent_generated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_logs_investor_id'), 'interaction_logs', ['investor_id'], unique=False)
    op.create_index(op.f('ix_interaction_logs_ir_id'), 'interaction_logs', ['ir_id'], unique=False)
    op.create_table('investors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('agency', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('email', sa.JSON(), nullable=True),
    sa.Column('wechat', sa.JSON(), nullable=True),
    sa.Column('phone', sa.JSON(), nullable=True),
    sa.Column('industry_tags', sa.JSON(), nullable=True),
    sa.Column('stage_pref', sa.JSON(), nullable=True),
    sa.Column('quota_range', sa.String(length=50), nullable=True),
    sa.Column('relationship_score', sa.SmallInteger(), nullable=True),
    sa.Column('profile_notes', sa.Text(length=4294967295), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('join_agency_date', sa.Date(), nullable=True),
    sa.Column('first_meeting_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ir_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('wechat_openid', sa.String(length=64), nullable=True),
    sa.Column('role', sa.Enum('ir', 'admin'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wechat_openid')
    )
    op.create_table('outreach_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('ir_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('meeting_minutes', 'industry_report', 'daily_push', 'milestone_message'), nullable=True),
    sa.Column('channel', sa.Enum('wechat', 'email', 'qmingpian'), nullable=True),
    sa.Column('content', sa.Text(length=4294967295), nullable=True),
    sa.Column('status', sa.Enum('draft', 'approved', 'sent', 'failed'), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_records_investor_id'), 'outreach_records', ['investor_id'], unique=False)
    op.create_index(op.f('ix_outreach_records_ir_id'), 'outreach_records', ['ir_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_records_ir_id'), table_name='outreach_records')
    op.drop_index(op.f('ix_outreach_records_investor_id'), table_name='outreach_records')
    op.drop_table('outreach_records')
    op.drop_table('ir_users')
    op.drop_table('investors')
    op.drop_index(op.f('ix_interaction_logs_ir_id'), table_name='interaction_logs')
    op.drop_index(op.f('ix_interaction_logs_investor_id'), table_name='interaction_logs')
    op.drop_table('interaction_logs')
    op.drop_index(op.f('ix_agent_traces_thread_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_ir_id'), table_name='agent_traces')
    op.drop_table('agent_traces')
    op.drop_index(op.f('ix_agent_feedback_trace_id'), table_name='agent_feedback')
    op.drop_index(op.f('ix_agent_feedback_ir_id'), table_name='agent_feedback')
    op.drop_table('agent_feedback')
    # ### end Alembic commands ###
