"""mvp_schema_phone_unique_token_interaction_fields

Revision ID: 6e30809e653d
Revises: 2b56329d65d3
Create Date: 2026-05-11 11:25:45.412495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e30809e653d'
down_revision: Union[str, None] = '2b56329d65d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaction_logs', sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('interaction_logs', sa.Column('duration_min', sa.SmallInteger(), nullable=True))
    op.add_column('interaction_logs', sa.Column('next_followup_at', sa.DateTime(), nullable=True))
    op.add_column('ir_users', sa.Column('tencent_meeting_token_encrypted', sa.LargeBinary(length=512), nullable=True))
    op.create_unique_constraint('uq_ir_users_phone', 'ir_users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ir_users_phone', 'ir_users', type_='unique')
    op.drop_column('ir_users', 'tencent_meeting_token_encrypted')
    op.drop_column('interaction_logs', 'next_followup_at')
    op.drop_column('interaction_logs', 'duration_min')
    op.drop_column('interaction_logs', 'occurred_at')
    # ### end Alembic commands ###
